SELECT 
--COUNT (*)
DISTINCT 
FIRST_NAME,
LAST_NAME
FROM HR.EMPLOYEES;

SELECT
    --CONCAT(FIRST_NAME, CONCAT(' ',LAST_NAME)) AS FULLNAME -- DOES THE SAME AS BELOW
    FIRST_NAME || ' ' || LAST_NAME AS FULLNAME
    ,SALARY
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID IN 
(SELECT EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 60);

--SAME AS ABOVE
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS FULLNAME
    ,SALARY
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN 
(SELECT DEPARTMENT_ID
FROM HR.DEPARTMENTS
WHERE DEPARTMENT_ID = 60);


CREATE TABLE PERSON
(
    ID INTEGER --GENERATED ALWAYS AS IDENTITY --ARTIFICIAL KEY
    ,NAME VARCHAR2(50)
    ,BIRTHDATE DATE
);

SELECT
    --TO_CHAR METHOD TURNS A DATE FORMAT INTO A STRING
    TO_CHAR(HIRE_DATE, 'MONTH') AS HIRE_DATE --ALIASING A NAME TO A COLUMN
FROM HR.EMPLOYEES;

INSERT INTO PERSON (NAME, BIRTHDATE)
(SELECT
    FIRST_NAME || ' ' || LAST_NAME AS FULLNAME
    ,HIRE_DATE AS BIRTHDATE
FROM HR.EMPLOYEES);

SELECT *
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

DELETE
FROM PERSON
WHERE NAME IN 
(SELECT FIRST_NAME || ' ' || LAST_NAME
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NULL);

ALTER TABLE PERSON ADD MONEY NUMBER(9,2);

INSERT INTO PERSON (MONEY)
WHERE NAME = FIRST_NAME || ' ' || LAST_NAME
SELECT 
--    SALARY
--    ,COMMISSION_PCT
    (SALARY * COMMISSION_PCT) + SALARY AS TOTAL
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--LOOK UP RULES FOR NORMAL FORMS
--NORMALIZATION

SELECT *
FROM HR.EMPLOYEES EMP
JOIN HR.DEPARTMENTS DEPT
    ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
    WHERE FIRST_NAME LIKE '%Kim%';
    
SELECT *
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.DEPARTMENTS DEPT
    ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
     WHERE FIRST_NAME LIKE '%Kim%';
   
--ERRORED BECAUSE OF GROUPING LOOK BELOW  
SELECT
    DEPARTMENT_NAME
    ,SUM(SALARY) AS TOTAL_SAL 
FROM HR.EMPLOYEES EMP
RIGHT JOIN HR.DEPARTMENTS DEPT
    ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID;
    
--CORRECT WAY    
SELECT
    DEPARTMENT_NAME
    ,ROUND(AVG(SALARY)) AS TOTAL_SAL 
FROM HR.EMPLOYEES EMP
RIGHT JOIN HR.DEPARTMENTS DEPT
    ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
    GROUP BY DEPARTMENT_NAME
    ORDER BY TOTAL_SAL DESC;
--ANYTHING THAT IS NOT AN AGRIGATE FUNCTION MUST BE GROUPED BY

SELECT
    DEPARTMENT_NAME
    ,ROUND(AVG(SALARY)) AS TOTAL_SAL 
FROM HR.EMPLOYEES EMP
RIGHT JOIN HR.DEPARTMENTS DEPT
    ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
    WHERE SALARY IS NOT NULL
    GROUP BY DEPARTMENT_NAME
    HAVING AVG(SALARY) > 10000
    ORDER BY TOTAL_SAL DESC;
    

SELECT 
    EMP.FIRST_NAME || ' ' || EMP.LAST_NAME AS EMP
    ,MANAGER.FIRST_NAME || ' ' || MANAGER.LAST_NAME AS MANAGER
FROM HR.EMPLOYEES EMP
LEFT JOIN HR.EMPLOYEES MANAGER
    ON EMP.MANAGER_ID = MANAGER.EMPLOYEE_ID;