insert into employee VALUES( '0', 'MARY', 'SNODDY', '119 HAZELNUT DR', 'NONE', 'JONESBOROUGH', 'TN', '37659');

INSERT INTO EMPLOYEE VALUES('1', 'MARY', 'SNODDY', '333 EAST WONDERVIEW AVE', 'NONE', 'ESTES PARK', 'CO', '80517');

INSERT INTO EMPLOYEE VALUES('3', 'JIMMY', 'SPRINKLES', '101 PEPPERMINT PARKWAY', 'APT 2', 'CANDYLAND', 'MS', '90210');

UPDATE EMPLOYEE SET FIRSTNAME = 'STEVEN' WHERE EMPLOYEEID = 2;
UPDATE EMPLOYEE SET LASTNAME = 'KING' WHERE EMPLOYEEID = 2;

DELETE FROM EMPLOYEE WHERE FIRSTNAME = 'JIMMY';